<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('users')->insert([
            [
                'name' => 'Михеева Татьяна Игоревна',
                'email' => 'monopolis.kazan@yandex.ru',
                'phone' => '+7 927 039-32-29',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Поздняков Евгений Владимирович',
                'email' => 'pozdnyakov.evgeniy@finplan.center',
                'phone' => '+7 916 264-89-78',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Рожкова Татьяна Рудольфовна',
                'email' => 'tatrozhkova@mail.ru',
                'phone' => '+7 911 607-43-51',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Объедков Никита Сергеевич',
                'email' => 'ns-promnadzor@yandex.ru',
                'phone' => '+7 985 458-32-38',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Голубева Валерия Евгеньевна',
                'email' => 'val-gol1@yandex.ru',
                'phone' => '+7 921 637-40-96',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Литаровская Любовь Петровна',
                'email' => 'lpl2004@inbox.ru',
                'phone' => '+7 910 418-47-35',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Кондратюк Татьяна Ивановна',
                'email' => 'ooo-konsalt@yandex.ru',
                'phone' => '+7 903 763-47-72',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Мустафаева Наима Алиевна',
                'email' => 'info@buro-unk.ru',
                'phone' => '+7 916 222-29-88',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Сергеев Александр Михайлович',
                'email' => 'buhgalter_rf@mail.ru',
                'phone' => '+7 985 233-09-88',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Татьяна Олеговна Падукова',
                'email' => '79521483478@yandex.ru',
                'phone' => '+7 952 148-34-78',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Халзанов Андрей Александрович',
                'email' => 'halzanov@mail.ru',
                'phone' => '+7 911 754-62-22',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Максимова Елена Валерьевна',
                'email' => 'prof-plus@bk.ru',
                'phone' => '+7 912 671-00-74',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Кондрашова Екатерина Геннадьевна',
                'email' => 'bulygina.katya@gmail.com',
                'phone' => '+7 903 964-13-66',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Резяпова Лилия Фаильевна',
                'email' => 'usha1974@yandex.ru',
                'phone' => '+7 917 407-08-32',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Мерзлякова Людмила Викторовна',
                'email' => 'info_office18@mail.ru',
                'phone' => '+7 928 293-50-47',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Губарец Жанна Феофановна',
                'email' => '6531199@mail.ru',
                'phone' => '+7 953 352-93-11',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Кейда Вера Владимировна',
                'email' => 'keida.vera@yandex.ru',
                'phone' => '+7 906 234-16-41',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Крун Владимир Николаевич',
                'email' => 'vladimir.krun@yandex.ru',
                'phone' => '+7 987 849-28-70',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Андриянов Владимир Иванович',
                'email' => '580299@mail.ru',
                'phone' => '+7 914 705-16-58',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Кочетова Виктория Викторовна',
                'email' => 'vikavv.83@mail.ru',
                'phone' => '+7 923 446-13-97',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Кочетова Виктория Викторовна',
                'email' => 'vikavv.83@mail.ru',
                'phone' => '+7 923 446-13-97',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Макаренкова Екатерина Сергеевна',
                'email' => 'Lastoshka@mail.ru',
                'phone' => '+7 916 002-08-20',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Роженцева Елена Леонидовна',
                'email' => 'Elena_2008-68@mail.ru',
                'phone' => '+7 966 666-51-53',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Пауль Валентина Валентиновна',
                'email' => 'Pww78@mail.ru',
                'phone' => '+7 904 988-90-94',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Ежова Галина',
                'email' => 'ezhova.forexspb@yandex.ru',
                'phone' => '+7 921 349-08-74',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Живаева Светлана Юрьевна',
                'email' => 's1306201125@yandex.ru',
                'phone' => '+7 950 640-50-32',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Ванцова Кристина Борисовна',
                'email' => 'vesta-buh@list.ru',
                'phone' => '+7 952 260-40-70',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Кузнецова Елена Геннадьевна',
                'email' => 'LGKuznetsova@yandex.ru',
                'phone' => '+7 985 774-45-27',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ],
            [
                'name' => 'Леонова Елена',
                'email' => 'elena.l2010@mail.ru',
                'phone' => '+7 910 003-58-11',
                'category_id' => 1,
                'balance' => 0,
                'email_notification' => '',
                'manager_id' => null,
                'contact_id' => '',
                'bonus' => 0,
                'with_bonus' => false,
                'role' => 'ROLE_USER',
                'is_registration' => true,
                'is_delete' => false,
                'was_online' => date("d-M-Y H:i:s"),
                'is_demo' => false,
                'created_at' => date("d-m-Y H:i:s"),
                'updated_at' => date("d-m-Y H:i:s"),
                'region_id' => 1,
                'is_block' => false,
                'password' => null
            ]
        ]);
    }
}
